### ISSUE TITLE
Metadata - Limnological

### ISSUE THREAD

**Issue by joshamilton** [McMahonLab/OMD-TOIL#2]
Update the McMahon lab sample book with limnological data. @amlinz will work with LRPs to do this.

**Comment by alexlinz** [comment]
LRPs are currently working on the data entry.

**Comment by alexlinz** [comment]
The data is all typed up! Currently it is in an Excel workbook with a tab in the workbook for each type of data collected. I will upload the portion of the data about each sample into the lab website sample book, but there is a substantial amount of other data that may be useful (filtering times, who collected the sample, boat movement during sampling). What are your thoughts on adding the Excel workbook to our repo? Or would separate .csv files for each tab in the workbook function better?

**Comment by joshamilton** [comment]
@amlinz No Excel workbooks, please, since we can't track them. It would be great to have all the data in separate .csv files.
